name: Terraform CI/CD

on:
  push:
    paths:
      - '**.tf'

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: |
          terraform output -json > tf_output.json
          echo "VM Naam: $(jq -r .vm_name.value tf_output.json)" > output.txt
          echo "IP Adres: $(jq -r .vm_ip.value tf_output.json)" >> output.txt
